### ISSUE TITLE
Referencing unexpected methods, due to dependency conflicts on  com.fasterxml.jackson.core:jackson-core:jar

### ISSUE THREAD

**Issue by HelloCoCooo** [buremba/netty-rest#9]
An issue similar to https://github.com/buremba/netty-rest/issues/8.

Mulptiple versions of **com.fasterxml.jackson.core:jackson-core:jar** exist in **netty-rest-netty-rest-0.106** . Based on Maven's _"nearest wins"_ strategy, only **com.fasterxml.jackson.core:jackson-core:jar:2.4.5** can be loaded, and **com.fasterxml.jackson.core:jackson-core:jar:2.8.9** will be shadowed.

Similarly, as shown in the following dependency tree, **io.swagger:swagger-core:jar:1.5.16** expects to reference **com.fasterxml.jackson.core:jackson-core:jar:2.8.9**. However, due to dependency conflicts, Maven actually loads **com.fasterxml.jackson.core:jackson-core:jar:2.4.5**. Consequenctly, **io.swagger:swagger-core:jar:1.5.16** has to invoke the methods included in the unexpected version **com.fasterxml.jackson.core:jackson-core:jar:2.4.5**, which may cause inconsistent semantic behaviors.

**_In total, there are 9 conflicting API pairs between these two library version._**

Likewise , method **org.rakam.server.http.SwaggerReader.isPrimitive(Type)** actually references method **com.fasterxml.jackson.core.util.JsonParserSequence.setnamesSet(Hashset)** in the unexpected version **ccom.fasterxml.jackson.core:jackson-core:jar:2.4.5** via the following invocation path:

```
<org.rakam.server.http.SwaggerReader: boolean isPrimitive(java.lang.reflect.Type)> C:\Users\Flipped\Desktop\project\netty-rest-netty-rest-0.106\.\target\classes
<org.rakam.server.http.ModelConverters: io.swagger.models.properties.Property readAsProperty(java.lang.reflect.Type)> C:\Users\Flipped\Desktop\project\netty-rest-netty-rest-0.106\.\target\classes
<io.swagger.converter.ModelConverterContextImpl: io.swagger.models.properties.Property resolveProperty(java.lang.reflect.Type,java.lang.'annotation'.Annotation[])> C:\Users\Flipped\.m2\repository\io\swagger\swagger-core\1.5.16\swagger-core-1.5.16.jar
<com.fasterxml.jackson.databind.MappingIterator: java.lang.Object next()> C:\Users\Flipped\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.4.5\jackson-databind-2.4.5.jar
<com.fasterxml.jackson.databind.MappingIterator: java.lang.Object nextValue()> C:\Users\Flipped\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.4.5\jackson-databind-2.4.5.jar
<com.fasterxml.jackson.databind.deser.impl.BeanAsArrayDeserializer: java.lang.Object deserialize(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext)> C:\Users\Flipped\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.4.5\jackson-databind-2.4.5.jar
<com.fasterxml.jackson.databind.deser.impl.InnerClassProperty: void deserializeAndSet(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,java.lang.Object)> C:\Users\Flipped\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.4.5\jackson-databind-2.4.5.jar
<com.fasterxml.jackson.databind.deser.std.EnumMapDeserializer: java.lang.Object deserializeWithType(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.jsontype.TypeDeserializer)> C:\Users\Flipped\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.4.5\jackson-databind-2.4.5.jar
<com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer: java.lang.Object deserializeTypedFromObject(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext)> C:\Users\Flipped\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.4.5\jackson-databind-2.4.5.jar
<com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer: java.lang.Object _deserializeTypedForId(com.fasterxml.jackson.core.JsonParser,com.fasterxml.jackson.databind.DeserializationContext,com.fasterxml.jackson.databind.util.TokenBuffer)> C:\Users\Flipped\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.4.5\jackson-databind-2.4.5.jar
<com.fasterxml.jackson.core.util.JsonParserSequence: com.fasterxml.jackson.core.util.JsonParserSequence.setnamesSet(Hashset)>
```

By further analyzing, the expected callee **com.fasterxml.jackson.core.util.JsonParserSequence.setnamesSet(Hashset)**, have different implementations from the actual callees with the same signatures (same method names, same paremeters) included in the unexpected (but actual loaded) version **com.fasterxml.jackson.core:jackson-core:jar:2.4.5**, which leads to different behaviors.

**Solution:**
Use the newer version **com.fasterxml.jackson.core:jackson-core:jar:2.8.9** to keep the version consistency.

**_The detailed informantion of the remaining 8 conflicting API pairs can be found in the following attachment._**

[9 conflicting API pairs in project netty-rest.txt](https://github.com/buremba/netty-rest/files/4174001/9.conflicting.API.pairs.in.project.netty-rest.txt)

**Dependency tree**-----
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ netty-rest ---
[INFO] org.rakam:netty-rest:jar:0.106
[INFO] +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] +- **com.fasterxml.jackson.core:jackson-core:jar:2.4.5:compile**
[INFO] +- io.airlift:log:jar:0.117:compile
[INFO] |  \- javax.inject:javax.inject:jar:1:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.4.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.4.0:compile
[INFO] |  \- (com.fasterxml.jackson.core:jackson-core:jar:2.4.5:compile - omitted for duplicate)
[INFO] +- com.jcraft:jzlib:jar:1.1.2:compile
[INFO] +- io.netty:netty-all:jar:4.0.33.Final:compile
[INFO] +- com.thoughtworks.paranamer:paranamer:jar:2.8:compile
[INFO] +- io.swagger:swagger-core:jar:1.5.16:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.2.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.22:compile
[INFO] |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.8.9:compile - omitted for conflict with 2.4.0)
[INFO] |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.8.9:compile - omitted for conflict with 2.4.5)
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.9:compile
[INFO] |  |  +- (**com.fasterxml.jackson.core:jackson-core:jar:2.8.9:compile - omitted for conflict with 2.4.5**)
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.17:compile
[INFO] |  +- io.swagger:swagger-models:jar:1.5.16:compile
[INFO] |  |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.8.9:compile - omitted for conflict with 2.4.0)
[INFO] |  |  +- (org.slf4j:slf4j-api:jar:1.7.22:compile - omitted for duplicate)
[INFO] |  |  \- io.swagger:swagger-annotations:jar:1.5.16:compile
[INFO] |  +- com.google.guava:guava:jar:20.0:compile
[INFO] |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.2.31:provided (scope not updated to compile)
[INFO] |  \- org.jetbrains:annotations:jar:13.0:provided
[INFO] +- org.jetbrains.kotlin:kotlin-reflect:jar:1.2.31:compile
[INFO] |  \- (org.jetbrains.kotlin:kotlin-stdlib:jar:1.2.31:compile - omitted for duplicate)
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test

Thanks!
Best regards,
Coco

**Comment by HelloCoCooo** [comment]
//Loaded version
public void setNamesSize(HashSet<String> names){ //names cannot be null
	this.size = names.size;
}
//Shadowed version
public void setNamesSize(HashSet<String> names){ //names can be null
	if (names != null) 
	this.size = names.size;
	else
	this.size = 0;
}
//Code snippet of entry method in host project
A.setNamesSize(entryNames);


Using the following test case to run on these two versions of methods separately starting from the entry method in your project, you can get a Java.lang.NullPointerException.
[netty-rest_test.txt](https://github.com/buremba/netty-rest/files/3183248/netty-rest_test.txt)

**Comment by HelloCoCooo** [comment]
@buremba  May I pull a request to fix this issue and https://github.com/buremba/netty-rest/issues/8 together?
Thanks for your attention.

**Comment by buremba** [comment]
Hey @HelloCoCooo, that makes sense. Feel free to create a PR for #8 and #9.
